const IMH_GOOGLE_SHEET_WEB_APP_URL = 'IMH_GOOGLE_SHEET_WEB_APP_URL';
const IMH_GOOGLE_SHEET_NAME = 'IMH_GOOGLE_SHEET_NAME';
const IMH_AUTOMATION_GOOGLE_SHEET_NAME = 'IMH_AUTOMATION_GOOGLE_SHEET_NAME';
const IMH_KM_DISTANCE_TO_COMPARISON = 'IMH_KM_DISTANCE_TO_COMPARISON';
const IMH_PRECENTAGE_UNDER_AVG_TO_COMPARISON = 'IMH_PRECENTAGE_UNDER_AVG_TO_COMPARISON';
const IMH_MAX_HOME_PRICE_TO_COMPARISON = 'IMH_MAX_HOME_PRICE_TO_COMPARISON';
const IMH_PRECENTAGE_PRICE_TO_SQF_AVG_TO_COMPARISON = 'IMH_PRECENTAGE_PRICE_TO_SQF_AVG_TO_COMPARISON';
const IMH_MINIMUM_PROPERTIES_TO_COMPS = 'IMH_MINIMUM_PROPERTIES_TO_COMPS';
const IMH_MINIMUM_DAYS_ON_MARKET = 'IMH_MINIMUM_DAYS_ON_MARKET';
const IMH_MAXIMUM_DAYS_ON_MARKET = 'IMH_MAXIMUM_DAYS_ON_MARKET';
const IMH_REHAB_SQF_PRICE_SMALL = 'IMH_REHAB_SQF_PRICE_SMALL';
const IMH_REHAB_SQF_PRICE_MEDIUM = 'IMH_REHAB_SQF_PRICE_MEDIUM';
const IMH_REHAB_SQF_PRICE_BIG = 'IMH_REHAB_SQF_PRICE_BIG';

export {
  IMH_GOOGLE_SHEET_WEB_APP_URL, 
  IMH_GOOGLE_SHEET_NAME, 
  IMH_AUTOMATION_GOOGLE_SHEET_NAME, 
  IMH_KM_DISTANCE_TO_COMPARISON, 
  IMH_PRECENTAGE_UNDER_AVG_TO_COMPARISON, 
  IMH_MAX_HOME_PRICE_TO_COMPARISON,
  IMH_PRECENTAGE_PRICE_TO_SQF_AVG_TO_COMPARISON,
  IMH_MINIMUM_PROPERTIES_TO_COMPS,
  IMH_MINIMUM_DAYS_ON_MARKET,
  IMH_MAXIMUM_DAYS_ON_MARKET,
  IMH_REHAB_SQF_PRICE_SMALL,
  IMH_REHAB_SQF_PRICE_MEDIUM,
  IMH_REHAB_SQF_PRICE_BIG,
}