export const MOTIVATION_KEYWORDS = [
  'Probate',
  'investors',
  'inherited',
  'foreclosure',
  'short sale',
  'preforeclosure',
  'pre-foreclosure',
  'pre foreclosure',
  'estate',
  'bring all offers',
  'vandalized',
  'uninsured',
  'must sell',
  'investor special',
  'special warranty deed',
  'quit claim deed',
  'heir',
  'heirs',
  'TLC',
  'motivated',
  'fixer',
  'fixer upper',
  'fixer-upper',
  'deferred maintenance',
  'repairs',
  'as-is',
  'as is',
  'relocation',
  'rented',
  'tenant',
  'do not disturb tenant',
  'owner will carry',
  'owner will carry 2nd',
  'owner finance',
  'owner will finance',
  'personal rep',
  'personal representative',
  'estate',
  'trustee',
  'basement issues',
  'basement repairs',
  'basement problems',
  'foundation issues',
  'foundation repairs',
  'foundation problems',
  'structural issues',
  'structural repairs',
  'structural problems',
  'no FHA',
  'lease option',
  'engineer report',
  'price change',
  'contract for',
  'cash',
  'vacant',
  'contractors special',
  'handyman special'
];
